name: Pull Request
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check PR title for Semantic Commit compliance
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            refactor
            docs
            perf
            style
            test
            chore
            ci
            revert
          requireScope: false
          disallowScopes: |
            [A-Z]+
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
